version: '3.8'

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie-config:/cowrie/cowrie-git/etc
      - ./cowrie-data:/cowrie/cowrie-git/var
    restart: unless-stopped

volumes:
  cowrie-config:
  cowrie-data: